apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  namespace: front-end
  labels:
    app: front-end-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-app
  template:
    metadata:
      labels:
        app: front-end-app
    spec:
      containers:
      - name: front-end-app
        image: 580103579984.dkr.ecr.ap-northeast-2.amazonaws.com/goorm3team/goormbank:Frontend66
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: front-end-deployment
#  namespace: front-end
#  labels:
#    app: front-end-app
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: front-end-app
#  template:
#    metadata:
#      labels:
#        app: front-end-app
#    spec:
#      containers:
#      - name: front-end-app
#        image: 580103579984.dkr.ecr.ap-northeast-2.amazonaws.com/goorm3team/goormbank:Frontend66
#        imagePullPolicy: Always
#        ports:
#        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: front-end
spec:
  type: LoadBalancer
  selector:
    app: front-end-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
